# Generated by Django 4.1.6 on 2023-03-19 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0002_tenniscourt_average_rating_tenniscourt_ratings_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenniscourt",
            name="phone",
        ),
    ]
