# Generated by Django 4.1.6 on 2023-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0003_remove_tenniscourt_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenniscourt",
            name="surface",
            field=models.CharField(
                choices=[("H", "Hard"), ("C", "Clay")], max_length=1
            ),
        ),
    ]
