# Generated by Django 4.1.6 on 2023-03-29 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("venues", "0006_alter_tenniscourt_users_liked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenniscourt",
            name="users_liked",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_liked",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
