# Generated by Django 4.1.6 on 2023-04-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0007_alter_tenniscourt_users_liked"),
    ]

    operations = [
        migrations.CreateModel(
            name="VenueTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/venue_traits"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tenniscourt",
            name="venue_traits",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="%(app_label)s_%(class)s_venue_traits",
                to="venues.venuetrait",
            ),
        ),
    ]
