# Generated by Django 4.1.6 on 2023-04-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venues", "0008_venuetrait_tenniscourt_venue_traits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenniscourt",
            name="venue_traits",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(app_label)s_%(class)s_venue_traits",
                to="venues.venuetrait",
            ),
        ),
    ]
