# Generated by Django 4.1.5 on 2023-01-30 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='start_date',
            new_name='registration_date',
        ),
    ]
