# Generated by Django 4.1.6 on 2023-03-29 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0008_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ("venues", "tenniscourt")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="object_id",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
