# Generated by Django 4.1.6 on 2023-03-29 14:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_user_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="object_id",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
