# Generated by Django 4.1.6 on 2023-03-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_user_object_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="object_id",
            new_name="venues_id",
        ),
    ]
