# Generated by Django 4.1.6 on 2023-03-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_rename_object_id_user_venues_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="venues_id",
            new_name="object_id",
        ),
    ]
