# Generated by Django 4.1.6 on 2023-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_rename_venues_id_user_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="object_id",
        ),
        migrations.AddField(
            model_name="user",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
