# Generated by Django 4.1.6 on 2023-03-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_user_object_id_user_object_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="object_id",
        ),
    ]
