# Generated by Django 4.1.5 on 2023-02-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="review",
            name="object_id",
        ),
    ]
