# Generated by Django 4.1.5 on 2023-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_alter_review_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
