# Generated by Django 4.1.5 on 2023-01-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='owner',
        ),
    ]
