# Generated by Django 4.1.5 on 2023-01-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_user_booking_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='user',
        ),
    ]
