# Generated by Django 4.1.5 on 2023-01-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_owner_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
