# Generated by Django 4.1.5 on 2023-02-03 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bookings', '0004_alter_booking_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': 'tenniscourt'}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
