# Generated by Django 4.1.5 on 2023-02-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0011_alter_booking_content_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Accepted"),
                    ("R", "Rejected"),
                    ("C", "Completed"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
