# Generated by Django 4.1.5 on 2023-02-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0012_alter_booking_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="date",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="start_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="start_date_time",
            field=models.DateTimeField(null=True),
        ),
    ]
