# Generated by Django 4.1.5 on 2023-02-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0013_remove_booking_date_remove_booking_start_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="start_date_time",
        ),
        migrations.AddField(
            model_name="booking",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="start_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="hours",
            field=models.IntegerField(null=True),
        ),
    ]
