# Generated by Django 4.1.5 on 2023-02-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0014_remove_booking_start_date_time_booking_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("A", "Accepted"), ("R", "Rejected"), ("C", "Completed")],
                default="A",
                max_length=1,
            ),
        ),
    ]
