# Generated by Django 4.1.6 on 2023-03-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0015_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("A", "Accepted"),
                    ("R", "Rejected"),
                    ("F", "Finished"),
                    ("C", "Cancelled"),
                ],
                default="A",
                max_length=1,
            ),
        ),
    ]
